### ISSUE TITLE
Problema na sequencia dos blocos INIT do servo motor

### ISSUE THREAD

**Issue by ahunaxi** [amadomaker/BIPES_Amado#41]
Quando os blocos INIT do Servo Motor ficam posicionados antes dos blocos INIT do Motor DC, eles não funcionam. 
![Image](https://github.com/user-attachments/assets/c13d3ef5-451a-4a4e-bf66-04c2c9af108f)

Se essa ordem for invertida, ambos funcionam normalmente.
![Image](https://github.com/user-attachments/assets/c7b58814-9135-4eb1-a544-92010ff63701)

**Comment by joaodrj** [comment]
O comportamento depende da ordem de inicialização dos PWM devido ao modo como o microcontrolador distribui recursos entre pinos PWM compartilhados. Quando os motores são inicializados antes dos servos, o sistema consegue alocar os recursos de forma mais eficiente. Isso ocorre porque os motores, que exigem menos precisão, "bloqueiam" recursos essenciais para que os servos, que precisam de ajustes mais constantes e precisos, funcionem sem interferências.

Como estamos usando quatro servos que executam muitas funções contínuas e sem delays, essa sequência ajuda a evitar sobrecarga e perda de sincronia nos sinais PWM. Inicializando os motores primeiro, o código garante estabilidade na alocação de PWM, evitando que os servos sejam afetados por conflitos de recursos.
